server:
  port: 8091
spring:
  application:
    name: payment-server
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    username: 'mayur'
    url: jdbc:postgresql://localhost:5432/payment
    password: 'mayur123'
com:
  mayur:
    OutboxEventPatternPOC:
      PaymentAcknowledge:
        LedgerRequest:
          kafka:
            bootstrap-servers: localhost:9093